// <auto-generated />
using System;
using BasicSyncServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BasicSyncServer.Migrations
{
    [DbContext(typeof(BasicSyncServerContext))]
    [Migration("20190305211254_BasicEntity")]
    partial class BasicEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BasicSyncServer.Models.BasicEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Hausnummer");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Ort");

                    b.Property<int>("RowVersion");

                    b.Property<string>("Straße");

                    b.HasKey("Id");

                    b.ToTable("BasicEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
